$(document).ready(function(){
	$('#district_select2').css('display','none');
	$('#district_select3').css('display','none');
	$('#dis_btn1').click(function(){
		$('#district_select2').css('display','block');
		$('#dis_btn2').click(function(){
			$('#district_select3').css('display','block');
		});
	});
	$("#prev2").click(function(){
		$('#second_select1').css('display','none');
		$('#first_select').css('display','block');
	});
	$("#prev3").click(function(){
		$('#second_select1').css('display','none');
		$('#first_select').css('display','block');
	});
	$("#prev4").click(function(){
		$('#second_select1').css('display','none');
		$('#first_select').css('display','block');
	});
	$("#prev5").click(function(){
		$('#second_select1').css('display','none');
		$('#first_select').css('display','block');
	});
});
